# Generated by Django 5.2.17 on 2026-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelfAuditSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("language", models.CharField(default="en", max_length=8)),
                (
                    "datetime_format",
                    models.CharField(default="%d.%m.%Y %H:%M:%S", max_length=32),
                ),
                ("min_severity", models.CharField(default="low", max_length=16)),
                ("smtp_host", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("smtp_security", models.CharField(default="starttls", max_length=16)),
                (
                    "smtp_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("smtp_password", models.TextField(blank=True, default="")),
                ("smtp_from", models.CharField(blank=True, default="", max_length=255)),
                (
                    "smtp_from_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("smtp_timeout", models.PositiveIntegerField(default=10)),
                ("smtp_auto_tls", models.BooleanField(default=False)),
                ("smtp_auth", models.BooleanField(default=False)),
                ("audit_email_enabled", models.BooleanField(default=False)),
                ("audit_email_recipients", models.TextField(blank=True, default="")),
                (
                    "audit_email_frequency",
                    models.CharField(default="daily", max_length=16),
                ),
                ("audit_email_weekday", models.PositiveSmallIntegerField(default=0)),
                ("audit_email_time", models.CharField(default="07:00", max_length=5)),
                ("audit_send_empty", models.BooleanField(default=False)),
                ("audit_email_attach_pdf", models.BooleanField(default=True)),
                ("audit_pdf_password", models.TextField(blank=True, default="")),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("system_snapshot", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SelfAuditSystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("kind", models.CharField(max_length=16)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("old", models.CharField(blank=True, default="", max_length=100)),
                ("new", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
        migrations.CreateModel(
            name="SelfAuditRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=100)),
                ("field", models.CharField(max_length=150)),
                ("severity", models.CharField(default="medium", max_length=16)),
                ("message", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("object_type", "field"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("object_type", "field"),
                        name="netbox_self_audit_rule_unique",
                    )
                ],
            },
        ),
    ]
