# Generated by Django 5.2.17 on 2026-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfauditsettings",
            name="default_period",
            field=models.CharField(default="today", max_length=16),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="report_header",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="track_system",
            field=models.BooleanField(default=True),
        ),
    ]
