# Generated by Django 5.2.17 on 2026-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0002_settings_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfauditsettings",
            name="severity_netbox",
            field=models.CharField(default="high", max_length=16),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="severity_plugin_added",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="severity_plugin_removed",
            field=models.CharField(default="critical", max_length=16),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="severity_plugin_version",
            field=models.CharField(default="medium", max_length=16),
        ),
    ]
