# Generated by Django 5.2.17 on 2026-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0003_system_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfauditsettings",
            name="group_by",
            field=models.CharField(default="object", max_length=16),
        ),
    ]
