# Generated by Django 5.2.17 on 2026-09-26 06:37

from django.db import migrations, models


def delivery_from_attach_pdf(apps, schema_editor):
    """Old setting "attach PDF" on -> PDF attachment, off -> audit in the e-mail body."""
    Settings = apps.get_model("netbox_self_audit", "SelfAuditSettings")
    for settings in Settings.objects.all():
        settings.audit_email_delivery = "pdf" if settings.audit_email_attach_pdf else "body"
        settings.save(update_fields=["audit_email_delivery"])


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0004_group_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfauditsettings",
            name="audit_email_delivery",
            field=models.CharField(default="pdf", max_length=8),
        ),
        migrations.RunPython(delivery_from_attach_pdf, migrations.RunPython.noop),
    ]
