# Generated by Django 5.2.17 on 2026-09-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0005_email_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfauditsettings",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="watchdog_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="watchdog_minutes",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
