# Generated by Django 5.2.17 on 2026-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0006_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfauditsettings",
            name="echo_reply",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="health_endpoint_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
