# Generated by Django 5.2.17 on 2026-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_self_audit", "0007_health_toggle_echo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("user", models.CharField(blank=True, default="", max_length=150)),
                ("event", models.CharField(db_index=True, max_length=32)),
                ("ok", models.BooleanField(default=True)),
                ("params", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-time", "-id"),
            },
        ),
        migrations.AddField(
            model_name="selfauditsettings",
            name="log_retention_days",
            field=models.PositiveSmallIntegerField(default=180),
        ),
    ]
